name: gbk_codec
description: GBK codec converter (enCode and deCode) library includes bytes codec.
version: 0.3.2
homepage: https://www.coodtec.com
author: John Wang <0@coodtec.com>

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  html: ^0.15.0

dev_dependencies:
  pedantic: ^1.11.0

